# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    format_listener:
        enabled: true
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: 'json' }
    exception:
        enabled: true
    # view:
    #     view_response_listener: 'force'
    #     formats:
    #         json: true
